### ISSUE TITLE
Potentially misparsed URL

### ISSUE THREAD

**Issue by silvanheller** [robinst/autolink-java#17]
Using:
`LinkExtractor.builder().linkTypes(setOf(LinkType.WWW, LinkType.URL)).build()`
and then `extractor.extractLinks()`

"man...http://i.imgur.com/rPRnI.jpg" 
is parsed as an URL, which seems wrong to me (not sure about the specs though)

**Comment by robinst** [comment]
Hey, thanks for the report. So, [RFC 3986 allows "." in the scheme](https://tools.ietf.org/html/rfc3986#section-3.1):

> scheme      = ALPHA *( ALPHA / DIGIT / "+" / "-" / "." )

Having said that, the only use of "." I can find in [IANA's registry](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml) is "z39.50". So maybe we could restrict it to only allow a single "." instead of multiple dots.

That would mean something like `foo.http://i.imgur.com` would still be recognized as a URL, but not your example.

What do you think?

**Comment by silvanheller** [comment]
Thanks for the reply! I see the problem with RFC 3986. In that case, I think in that case it's maybe better to leave this as documented behavior which programmers have to catch since I feel like Protocol adherence > convenience. 
Especially since your proposed solution does not fully fix the problem. What would solve it is an extractor which only looks for HTTP[s] schemes and strips everything else from the scheme, but i feel like that's outside the scope of this library.
Funnily enough, twitter doesn't have that problem on their [Conformance List](https://github.com/twitter/twitter-text/blob/master/conformance/extract.yml)

**Comment by robinst** [comment]
Sounds good! I've added a note to the README now, thanks.

(And yeah, Twitter's list is missing some interesting edge cases :).)
