### ISSUE TITLE
Version 0.10.2 broke binary compatibility

### ISSUE THREAD

**Issue by aalmiray** [robinst/autolink-java#42]
Version `0.10.1` was published with Java 7 as baseline.
```
$ jarviz bytecode show --gav org.nibor.autolink:autolink:0.10.1
subject: autolink-0.10.1.jar
Unversioned classes. Bytecode version: 51 (Java 7) total: 19
```

Version `0.10.2` was published with Java 9 as baseline.
```
$ jarviz bytecode show --gav org.nibor.autolink:autolink:0.10.2
subject: autolink-0.10.2.jar
Unversioned classes. Bytecode version: 53 (Java 9) total: 20
```

I understand the library wants to move to newer Java versions, matter of fact version `0.11.0` also requires Java 9 as a minimum (👍). However, bumping bytecode compatibility on a build/patch release, even pre `1.0.0`, well ... that was unexpected.

Please consider reverting to Java 7 _if and only if_ a `0.10.3` were to be released in the future.

**Comment by robinst** [comment]
Oh no, that was not intended :(. As you can see in [CHANGELOG.md](https://github.com/robinst/autolink-java/blob/main/CHANGELOG.md), version 0.10.2 was not meant to be published. I don't remember fully but I probably used the maven release plugin wrong and before I noticed I had published 0.10.2 instead of 0.11.0.

Thanks for reporting. I don't think there's a way to yank the version from Maven Central unfortunately.

> Please consider reverting to Java 7 _if and only if_ a `0.10.3` were to be released in the future.

👍 not planned but I'll keep it in mind.
