### ISSUE TITLE
Dealing with | symbol

### ISSUE THREAD

**Issue by ymmark0** [robinst/autolink-java#6]
Hey Robin
We're using your library however I'd like to modify it to account for | symbols and www.
We have templates with urls such as
http://test.com|test site  and sometimes we get things like www.blah

The lib is extracting the first as http://test.com|test and doesn't deal with the second.

I'll fix this myself, but are you interested in pull requests related to these?

Cheers

**Comment by robinst** [comment]
Hey! I'm definitely interested in detecting `www.` style links. It could be another `LinkType` so that detection can be enabled/disabled using `LinkExtractor.Builder#linkTypes`. If you could do that as a PR, that would be great :).

As for recognizing `|` as a terminating character, that would be at odds with the existing logic. Currently, the only thing that causes a definite end of a URL is whitespace, and then we backtrack from there.

So I would recommend splitting the `|xyz` from the URL in a step after link detection, in your own code.

**Comment by ymmark0** [comment]
Hey Robin,
Ok, that sounds fine.  The | symbol is my first priority and then I’ll get onto www.  
I may have the odd question if you don’t mind?

Cheers
Mark.

**Comment by ymmark0** [comment]
Hey Robin
When you say link detection, do you mean link extraction?  

Cheers
Mark.

**Comment by robinst** [comment]
> I may have the odd question if you don’t mind?

Sure :).

> When you say link detection, do you mean link extraction?

Yeah, I use them interchangeably.
